# Generated by Django 5.2.4 on 2025-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alma', '0002_alter_user_options_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
