# Generated by Django 5.2.4 on 2025-07-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alma', '0004_alter_product_barcode_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
